steps:
  - label: ":shell: Tests"
    plugins:
      docker-compose#v3.8.0:
        run: tests

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v3.0.0:
        id: ecr

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.2.0:
        files: hooks/**
    skip: "Shellcheck doesn't pass right now"
